require("dotenv").config({ silent: true });

module.exports = {
	environment: process.env.NODE_ENV || "production",
	port: process.env.PORT || 80,
	aws: {
		awsMediaBaseUrl: process.env.AWS_MEDIA_BASE_URL,
		awsKeyId: process.env.AWS_KEY_ID,
		awsSecretKey: process.env.AWS_SECRET_KEY,
		awsBucketName: process.env.AWS_BUCKET_NAME || "",
	},
	google: {
		clientId: process.env.GOOGLE_API_OAUTH_CLIENT_ID
	},
	database: {
		poolMax: 5,
		poolMin: 0,
		poolAcquire: 30000,
		poolIdle: 10000,
		databaseUrl: process.env.DATABASE_URL,
		ssl: process.env.PGSSLMODE == "true" ? true : false,
	},
	defaultApiKey: process.env.DEFAULT_API_KEY,
	corsUrl: process.env.CORS_URL ? process.env.CORS_URL.split(",") : "",
	defaultEmail: process.env.DEFAULT_EMAIL,
	defaultFromEmail: process.env.DEFAULT_FROM_EMAIL,
	defaultLeaveEmail: process.env.DEFAULT_LEAVE_EMAIL,
	jobsEmail: process.env.JOB_EMAIL,
	baseUrl: process.env.BASE_URL,
	webUrl: process.env.WEB_URL,
	defaultTimeZone: process.env.TIMEZONE || "Asia/Kolkata",
	resetTime: process.env.RESET_TIME || "06:00:00",
	sendGridAPIKey: process.env.SENDGRID_API_KEY,
	trelloAppKey: process.env.TRELLO_APP_KEY,
	trelloAppToken: process.env.TRELLO_APP_TOKEN,
	shopifyPassword: process.env.SHOPIFY_PASSWORD,
	tracker_db_host: process.env.TRACKER_DB_HOST,
	tracker_db_user: process.env.TRACKER_DB_USER,
	tracker_db_database: process.env.TRACKER_DB_DATABASE,
	tracker_db_password: process.env.TRACKER_DB_PASSWORD,
	slack_user_oauth_access_token: process.env.SLACK_USER_OAUTH_ACCESS_TOKEN,
	slack_bot_oauth_access_token: process.env.SLACK_BOT_OAUTH_ACCESS_TOKEN,
	slack_channel_id: process.env.SLACK_CHANNEL_ID,
	allowed_attendance_ips: process.env.ALLOWED_ATTENDANCE_IPS,
	schedulerApiKey: process.env.SCHEDULER_API_KEY,
	slackClientId: process.env.SLACK_CLIENT_ID,
	slackClientSecret: process.env.SLACK_CLIENT_SECRET,
	whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID,
	whatsappBusinessAccountId: process.env.WHATSAPP_BUSINESS_ACCOUNT_ID,
	whatsappApiVersion: process.env.WHATSAPP_API_VERSION,
	sslCertificate: process.env.SSL_CERTIFICATE,
	sslKey: process.env.SSL_KEY
};
